### ISSUE TITLE
 if you are using GNU date ***    cv::resize()

### ISSUE THREAD

**Issue by zpbdlut** [XiaohangZhan/mix-and-match#2]
Hi, when I tried to train the model (sh run_graph.sh), I have a problem: can anyone tell me how to fix it?

I0319 21:39:59.797385  7363 solver.cpp:372] Solving AlexNet
I0319 21:39:59.797394  7363 solver.cpp:373] Learning Rate Policy: step
*** Aborted at 1521466800 (unix time) try "date -d @1521466800" if you are using GNU date ***
PC: @     0x7fc32322f38d cv::resize()
*** SIGSEGV (@0x1010000) received by PID 7363 (TID 0x7fc32b54aa00) from PID 16842752; stack trace: ***
    @     0x7fc3215e6330 (unknown)
    @     0x7fc32322f38d cv::resize()
    @     0x7fc2cc09911d pyopencv_cv_resize()
    @     0x7fc322604b94 (unknown)
    @     0x7fc322604b19 (unknown)
    @     0x7fc322606c3d (unknown)
    @     0x7fc322606dd0 (unknown)
    @     0x7fc3225db0a3 (unknown)
    @     0x7fc32257fd6d (unknown)
    @     0x7fc3225db0a3 (unknown)
    @     0x7fc32266e5f7 (unknown)
    @     0x7fc3225895d7 (unknown)
    @     0x7fc2c9dbfaef caffe::PythonLayer<>::Forward_cpu()
    @     0x7fc32ad27389 caffe::Net<>::ForwardFromTo()
    @     0x7fc32ad277b7 caffe::Net<>::ForwardPrefilled()
    @     0x7fc32ad12705 caffe::Solver<>::Step()
    @     0x7fc32ad1302f caffe::Solver<>::Solve()
    @           0x407910 train()
    @           0x405db6 main
    @     0x7fc32122ef45 (unknown)
    @           0x40639b (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by XiaohangZhan** [comment]
Hi,
Pls check the parameter `output_size` and the availability of bottom[0].data in `RandomSamplingLayer ` in "sampling_layers.py".
