### ISSUE TITLE
Question regarding node label

### ISSUE THREAD

**Issue by cassie101** [XiaohangZhan/mix-and-match#3]
"...resize them to a fixed size of 128×128. Then we extract “pool5”  feature  of  these  patches  from  the  CNN  for  later usage. We assign the patches’ unique labels as the central pixel labels using the corresponding label maps. Then we perform  the  iterative  strategy  to  construct  the  graph  as discussed in the methodology section."

Hi @XiaohangZhan, I'm confused at the part where patches are labeled. After getting a feature at pool5 of size 4x4 from input 128x128, how does one "assign the patches’ unique labels as the central pixel labels using the corresponding label maps" from a ground truth label maps of 4x4? 

Thank you.

**Comment by XiaohangZhan** [comment]
We use the central pixel of the 128x128 patch to lookup its label, rather than the 4x4 patch.

**Comment by cassie101** [comment]
Hi @XiaohangZhan, thank you for your prompt reply. For an example, this image could be labeled as 'background' instead of 'human' because the central pixel can be 'background'. Is that correct?
![example](https://user-images.githubusercontent.com/42600012/62431399-f01e4a00-b759-11e9-9a8d-f535a5411f37.png)

**Comment by XiaohangZhan** [comment]
Yes, it will not be labeled as human. However, it may not be labeled as background as long as the parameter "by_ovlp" is True. According to line 82 in the [code](https://github.com/XiaohangZhan/mix-and-match/blob/e538d01d4b01c1593e24a49e6f1a2b0628b46dfc/resources/create_patch.py#L82), when by_ovlp is True, the patch with lower overlap with its category has a lower priority to be chosen. In my experiments, "by_ovlp" is switched off to encouraging hard samples. However, you may try to switch it on to see the difference.

**Comment by cassie101** [comment]
@XiaohangZhan thank you for your clarification, I understand better now.
